version: "3.7"

services:
  api:
    hostname: api
    container_name: api
    restart: always
    volumes:
      - .:/app
    ports:
      - 8080:${SERVER_PORT}
    image: clearlinux/node:latest
    working_dir: /app
    command: sh docker/dev.sh
    networks:
      - api-net

  mysql:
    image: mysql:8.0.29
    container_name: api-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laka
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
